name: Parse TOML Python Version and Install it
description: "This action reads the Python version from a pyproject.toml file and installs the specified version of Python using the setup-python action."
outputs:
  python-version:
    description: "The Python version to install"
    value: ${{ steps.get-python.outputs.python-version }}

runs:
  using: "composite"
  steps:
    - name: Grab Repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: Extract Python Version
      id: get-python
      shell: bash
      run: |
        # Extract Python version, removing version constraint characters
        PYTHON_VERSION=$(cat pyproject.toml | \
          sed -n 's/.*python\s*=\s*"\([^"]*\)".*/\1/p' | \
          sed -E 's/[~^<>=]+//g')

        # Check if version was extracted
        if [ -z "$PYTHON_VERSION" ]; then
          echo "Failed to extract Python version from pyproject.toml"
          exit 1
        fi

        echo "Extracted Python version: $PYTHON_VERSION"
        echo "python-version=$PYTHON_VERSION" >> $GITHUB_OUTPUT

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ steps.get-python.outputs.python-version }}

    - name: Verify Python Version
      shell: bash
      run: |
        python --version
